services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel12-app
    container_name: laravel12-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - laravelnet
    depends_on:
      - db
      - redis

  webserver:
    image: nginx:stable-alpine
    container_name: laravel12-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravelnet

  db:
    image: mysql:8.0
    container_name: laravel12-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravelnet

  redis:
    image: redis:7-alpine
    container_name: laravel12-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravelnet

networks:
  laravelnet:

volumes:
  dbdata:
